# Generated by Django 4.2 on 2023-05-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_division', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_division.contracts', verbose_name='Контракт'),
        ),
    ]
