# Generated by Django 4.2 on 2023-05-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_division', '0002_alter_acts_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professor_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_division.professors'),
        ),
    ]
