# Generated by Django 4.2 on 2023-05-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_division', '0004_alter_contracts_course_alter_contracts_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_division.professors', verbose_name='Преподаватель'),
        ),
    ]
